from app.ai.gemini_service import ask_gemini


def chat_with_ai(
    customer,
    account,
    spending,
    health,
    question,
    offer=None,
):

    offer_context = ""

    if offer:
        if offer.get("type") == "loan":
            offer_context = f"""
Personalized Financing Offer:
- Offer Type: Personal Loan
- Loan Amount: ${float(offer.get("amount", 0)):,.2f}
- Monthly Deduction: ${float(offer.get("monthly_emi", 0)):,.2f}
- Tenure: {offer.get("tenure_months", 0)} months
- Interest Rate: {offer.get("interest_rate", 0)}%

This loan offer has been generated by the banking system because
the requested purchase cannot safely be funded from the customer's
current balance.

IMPORTANT:
If this loan offer is relevant to the customer's question, clearly
mention the loan amount, monthly deduction, tenure and interest rate
in your answer. Do not invent different loan values.
"""

        elif offer.get("type") == "purchase":
            offer_context = f"""
Personalized Purchase Offer:
- Product: {offer.get("product", "Purchase")}
- Offer Amount: ${float(offer.get("amount", 0)):,.2f}
- Discount: {offer.get("discount_percent", 0)}%

This is an affordable purchase offer.

IMPORTANT:
Mention the purchase offer only when it is relevant to the customer's
question. Do not describe it as a loan and do not mention a monthly
deduction for a normal purchase.
"""

    prompt = f"""
You are an AI Banking Assistant.

Customer:
{customer.full_name}

Annual Salary:
{customer.salary}

Current Balance:
{account.balance}

Savings:
{account.savings}

Financial Health:
{health["financial_health_score"]}

Status:
{health["status"]}

Highest Spending Category:
{spending["highest_spending_category"]}

Category Breakdown:
{spending["category_breakdown"]}

Customer Question:
{question}

{offer_context}

Answer as an experienced banking financial advisor.

Give practical, financially responsible advice.

If a personalized loan offer is provided above, include its
important details in the response:
loan amount, monthly deduction, tenure and interest rate.

Clearly explain why the loan is being recommended when the requested
purchase exceeds the customer's available balance or when the
customer's balance is below the banking system's safety threshold.

Never allow or recommend a purchase that would make the customer's
account balance negative.

Do not invent financial figures that conflict with the personalized
offer provided above.

Maximum 200 words.

Do not create a payment link in the answer.
"""

    return ask_gemini(prompt)
